// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEtDdij5_L4y0wQ75ZpqMKeQAZekWvHI',
    appId: '1:648151978741:android:bb526557b739609dbfebbc',
    messagingSenderId: '648151978741',
    projectId: 'testus-app',
    storageBucket: 'testus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-D_TG8b4pWgRgHHXjc32yZA7uVNKfwFU',
    appId: '1:648151978741:ios:bef68bf8f4095820bfebbc',
    messagingSenderId: '648151978741',
    projectId: 'testus-app',
    storageBucket: 'testus-app.firebasestorage.app',
    androidClientId: '648151978741-cuqclu86us8ra4m6vanjh8ijfi1dvvbs.apps.googleusercontent.com',
    iosClientId: '648151978741-kg42bt8pljjmp80eppb2g9bq5ij87d73.apps.googleusercontent.com',
    iosBundleId: 'com.testus.devon.studio.app',
  );
}
